version: "3.8"

services:
  backend:
    build:
      context: ./.docker
    container_name: backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./.docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - doppus_network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: doppus
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - doppus_network

  frontend:
    image: node:14
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - doppus_network

volumes:
  db_data:

networks:
  doppus_network:
    driver: bridge
